[microsoft-edge-stable]
source = "rpmrepo"
repo = "https://packages.microsoft.com/yumrepos/edge"
pkg = "microsoft-edge-stable"
arch = "x86_64"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"

[visual-studio-code]
source = "github"
github = "microsoft/vscode"
use_latest_release = true
prefix = "v"

[qt-sudo]
source = "github"
github = "aarnt/qt-sudo"
use_latest_release = true
prefix = "v"

[octopi]
source = "github"
github = "aarnt/octopi"
use_latest_release = true
prefix = "v"

# [udev-usb-sync]
# source = "gitlab"
# host = "gitlab.manjaro.org"
# gitlab = "applications/udev-usb-sync"
# use_latest_release = true
# prefix = "v"

[lm-studio]
source = "regex"
url = "https://lmstudio.ai/download"
regex = '\\"linux\\":\{\\"x64\\":\{\\"version\\":\\"([\d\.]+)\\"'