[microsoft-edge-stable]
source = "rpmrepo"
repo = "https://packages.microsoft.com/yumrepos/edge"
pkg = "microsoft-edge-stable"
arch = "x86_64"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"

[visual-studio-code]
source = "cmd"
cmd = "curl -s 'https://update.code.visualstudio.com/api/update/linux-x64/stable/latest' | jq -r '.productVersion'"

[qt-sudo]
source = "github"
github = "aarnt/qt-sudo"
use_latest_release = true
prefix = "v"

[octopi]
source = "github"
github = "aarnt/octopi"
use_latest_release = true
prefix = "v"

[claude-code]
source = "regex"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest"
regex = ".+"

# [lm-studio]
# source = "cmd"
# cmd = "curl -sIL -o /dev/null -w '%{url_effective}\\n' https://lmstudio.ai/download/latest/linux/x64 | sed -E 's|.*x64/([0-9]+\\.[0-9]+\\.[0-9]+)-([0-9]+).*|\\1.\\2|'"