[microsoft-edge-stable]
source = "rpmrepo"
repo = "https://packages.microsoft.com/yumrepos/edge"
pkg = "microsoft-edge-stable"
arch = "x86_64"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"

[visual-studio-code]
source = "cmd"
cmd = "curl -s 'https://update.code.visualstudio.com/api/update/linux-x64/stable/latest' | jq -r '.productVersion'"

[qt-sudo]
source = "github"
github = "aarnt/qt-sudo"
use_latest_release = true
prefix = "v"

[octopi]
source = "github"
github = "aarnt/octopi"
use_latest_release = true
prefix = "v"