[microsoft-edge-stable]
source = "rpmrepo"
repo = "https://packages.microsoft.com/yumrepos/edge"
pkg = "microsoft-edge-stable"
arch = "x86_64"

[yay]
source = "github"
github = "Jguer/yay"
use_latest_release = true
prefix = "v"