name: Arch Package CI/CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y libxml2-utils

      - name: Check for Updates
        id: check
        run: ./update-version.sh

      - name: Build Package and Generate SRCINFO
        if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: docker://archlinux:base-devel
        with:
          args: /bin/bash -c "
            pacman -Syu --noconfirm git &&
            useradd builduser -m &&
            passwd -d builduser &&
            printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers &&
            chown -R builduser:builduser . &&
            su builduser -c 'makepkg --printsrcinfo > .SRCINFO' &&
            su builduser -c 'makepkg -s --noconfirm'
            "

      - name: Fix File Permissions
        if: steps.check.outputs.UPDATE_NEEDED == 'true'
        run: sudo chown -R $USER:$USER .

      - name: Commit PKGBUILD Changes
        if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: ${{ steps.check.outputs.NEW_VERSION }}"
          file_pattern: 'PKGBUILD .SRCINFO'

      - name: Create Repository Database
        if: steps.check.outputs.UPDATE_NEEDED == 'true'
        run: |
          mkdir -p release_dist
          mv *.pkg.tar.zst release_dist/
          docker run --rm -v $PWD/release_dist:/repo archlinux:base-devel /bin/bash -c "
            cd /repo && 
            repo-add -n shelter-arch-aur.db.tar.gz *.pkg.tar.zst
          "

      - name: Delete Old Release
        if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: x86_64
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: x86_64
          name: "Arch Linux Repository (x86_64)"
          body: "Updated: ${{ steps.check.outputs.NEW_VERSION }}"
          files: release_dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
