name: Arch Package CI/CD

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      check_for_updates:
        description: 'Check upstream updates? (Uncheck to build current PKGBUILD as-is)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get install -y libxml2-utils

      - id: check
        run: |
          chmod +x ./update-version.sh
          if [[ "${{ github.event_name }}" == "schedule" || "${{ inputs.check_for_updates }}" == "true" ]]; then
            ./update-version.sh
          else
            VER=$(grep "^pkgver=" PKGBUILD | cut -d'=' -f2)
            REL=$(grep "^pkgrel=" PKGBUILD | cut -d'=' -f2)
            echo "UPDATE_NEEDED=true" >> "$GITHUB_OUTPUT"
            echo "NEW_VERSION=${VER}-${REL}" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: docker://archlinux:base-devel
        with:
          args: /bin/bash -c "
            pacman -Syu --noconfirm git &&
            useradd builduser -m &&
            passwd -d builduser &&
            printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers &&
            chown -R builduser:builduser . &&
            su builduser -c 'makepkg --printsrcinfo > .SRCINFO' &&
            su builduser -c 'makepkg -s --noconfirm'
            "

      - if: steps.check.outputs.UPDATE_NEEDED == 'true'
        run: sudo chown -R $USER:$USER .

      - if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: ${{ steps.check.outputs.NEW_VERSION }}"
          file_pattern: 'PKGBUILD .SRCINFO'

      - if: steps.check.outputs.UPDATE_NEEDED == 'true'
        run: |
          mkdir -p release_dist
          mv *.pkg.tar.zst release_dist/
          docker run --rm -v $PWD/release_dist:/repo archlinux:base-devel /bin/bash -c "
            cd /repo && 
            repo-add -n shelter-arch-aur.db.tar.gz *.pkg.tar.zst
          "

      - if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: x86_64
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.check.outputs.UPDATE_NEEDED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: x86_64
          name: "Arch Linux Repository (x86_64)"
          body: "Package Updated: ${{ steps.check.outputs.NEW_VERSION }}"
          files: release_dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
