name: main

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'
  

env:
  UPDATE_STATE: 'false'

jobs:
  update-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Install libxml2-utils
        run: sudo apt install -y libxml2-utils
      - name: Run update check
        run:  ./update-version.sh
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        env:
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        with:
          commit_message: new version ${{ env.F_TIME }}
          tagging_message: ${{ env.F_TIME }}
