name: main

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  

env:
  UPDATE_STATE: 'false'

jobs:
  update-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run update check
        run:  echo "UPDATE_STATE=$(./update-version.sh | tail -n1)" >> $GITHUB_ENV && ./clear.sh
      - if: ${{ env.UPDATE_STATE != 'false' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: new-version ${{ env.UPDATE_STATE }}
          tagging_message: ${{ env.UPDATE_STATE }}
      - if: steps.commit.outcome == 'success'
        uses: onenowy/archlinux-acer-predato/.github/workflows/release.yml@${{ env.UPDATE_STATE }}
