name: main

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  

env:
  UPDATE_STATE: 'false'

jobs:
  update-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Run update check
        run:  echo "UPDATE_STATE=$(./update-version.sh | tail -n1)" >> $GITHUB_ENV
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - if: ${{ env.UPDATE_STATE != 'false' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        env:
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        with:
          commit_message: new version ${{ env.F_TIME }}
          tagging_message: ${{ env.F_TIME }}
