name: main

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  

env:
  UPDATE_STATE: 'false'

jobs:
  update-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      commit_result: ${{ steps.commit.outcome }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Run update check
        run:  echo "UPDATE_STATE=$(./update-version.sh | tail -n1)" >> $GITHUB_ENV
      - if: ${{ env.UPDATE_STATE != 'false' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: new-version ${{ env.UPDATE_STATE }}
          tagging_message: ${{ env.UPDATE_STATE }}
